/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.awt.*;
import java.util.Arrays;

public class App {
    public static String getUnicornData() {
        return "{\"hornColor\": \"white and shimmery\", \"name\":\"sparkles\"}";
    }

    public static void main(String[] args) {
        Unicorn u = new Unicorn("Rainbow", "rainbow");
        Unicorn u2 = new Unicorn("Bono", "gray");

        Unicorn[] unicorns = new Unicorn[]{u, u2};
        // no way to set u.maneLength
        Gson gson = new GsonBuilder().serializeNulls().create();

        String unicornsJsonString = gson.toJson(unicorns);
        System.out.println(unicornsJsonString);

        System.out.println(Arrays.toString(gson.fromJson(unicornsJsonString, Unicorn[].class)));
        System.out.println(Arrays.toString(gson.fromJson(unicornsJsonString, Rhinocerous[].class)));

//        Unicorn unicornFromJsonData = gson.fromJson( getUnicornData(), Unicorn.class );
//        System.out.println(unicornFromJsonData);
    }
}

class Node {
    String value;
    Node next;

    public Node(String value, Node next) {
        this.value = value;
        this.next = next;
    }
}
