/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransform;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        File bitmapFile = new File("./java_clr_hori.bmp");
        BufferedImage bufferedImage = null;
        try {
            bufferedImage = ImageIO.read(bitmapFile);
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Fatal error reading file");
            System.exit(1);
        }
        Bitmap bitmap = new Bitmap(bufferedImage);
        bitmap.makeBlackAndWhite();
        try {
            bitmap.outputToFile("./java-bw.bmp");
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println(new App().getGreeting());
    }
}
