/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberfacts;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {
    // https://www.baeldung.com/java-http-request
    public static String getNumberFact() {
        // make a request to the number facts API
        try {
            URL url = new URL("http://numbersapi.com/random/trivia?json");
    //  &apiKey=" +System.getenv("YELP_API_KEY")
            HttpURLConnection con = (HttpURLConnection) url.openConnection();

            // this line of code actually goes to the internet!
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));


            // get json data in response
            // use Gson to parse json string into a number fact object
            Gson gson = new Gson();
            NumberFact numberFact = gson.fromJson(reader, NumberFact.class);
            // access the text of the number fact
            // return that text so that it can be printed
            return numberFact.text;
        } catch (IOException e) {
            System.out.println(e);
            return "Two is the smallest prime number";
        }
    }

    public static void main(String[] args) {
        System.out.println(getNumberFact());
    }
}
