/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleDemo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] reverse(int[] inputArr) {
        for (int i = 0; i < inputArr.length / 2; i++) {
            int temp = inputArr[i];
            inputArr[i] = inputArr[inputArr.length - 1 - i];
            inputArr[inputArr.length - 1 - i] = temp;
        }
        return inputArr;
    }
}
