/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whiteboards;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testFibonacci() {
        Library classUnderTest = new Library();
        assertEquals("4th fib is 3", 3, classUnderTest.fibonacci(4));
        // 0  1  2  3  4  5  6  7   8   9   10  11  12
        // 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144
        assertEquals("12th fib is 144", 144, classUnderTest.fibonacci(12));
    }
}
