/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleDemo; // single line comments are the same too

import org.junit.Test;
import static org.junit.Assert.*;

// what is happening in this file?
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        // create an instance of Library
        Library classUnderTest = new Library();
        // check that it's returning the thing we expected
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        // check that the code you wrote does the right thing
    }

    @Test
    public void testReverse_emptyArray() {
        Library libraryForTesting = new Library();
        int[] inputArr = new int[0];
        assertArrayEquals("reversing an empty array should give an empty array", // message to developer
                new int[0], // expected value
                libraryForTesting.reverse(inputArr)); // actual value
    }

    @Test
    public void testReverse_basicArray() {
        Library libraryForTesting = new Library();
        int[] inputArr = new int[]{1, 2, 3, 17, 4};
        int[] expectedOutput = new int[]{4, 17, 3, 2, 1};
        assertArrayEquals("reversing a basic array should give back the values in the opposite order",
                expectedOutput,
                libraryForTesting.reverse(inputArr));
    }

    // the other test cases that I would test if I had the time
    // test where a bunch of the numbers are the same
    // test with negative numbers
    // test with a palindrome array
    // test a really large array
    // test an even-length and an odd-length array
}
