/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

public class Library {
    public int addNumbers(PairOfNumbers numbers, Context c) {
        LambdaLogger logger = c.getLogger();
        logger.log("received the numbers " + numbers.a + " and " + numbers.b);
        return numbers.a + numbers.b;
    }
}

class PairOfNumbers{
    int a;
    int b;

    public void setA(int a) {
        this.a = a;
    }

    public void setB(int b) {
        this.b = b;
    }
}
