/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AliceReader reader = new AliceReader();
        String mostCommonCharacter = reader.findMostCommonCharacter();
        System.out.println(String.format("The most common character in Alice in Wonderland is %s.", mostCommonCharacter));
    }
}
